### PR TITLE
Add a licensing page

### PR DESCRIPTION
**Pull request by Hjdskes**
Hello!

Thank you for creating this awesome theme, I'm really liking how my website is starting to look!

That said, I was looking to add a link to a licensing page in the bottom of my pages. This is a PR to start a discussion before I (or you, styling websites is not really my strong suit :stuck_out_tongue_closed_eyes:) set the layout in stone.

Right now, there is a configurable copyright message displayed to the left of the icons in the footer of the page:

screenshot from 2017-02-21 20-17-45

This links to `{{ .Site.BaseURL}}/license`, which can contain anything as usual. This file is skipped when scanning for links to add on the homepage. The displayed copyright message is set in `config.toml` like so: `copyright = "Copyright © 2016, 2017 Jente Hidskes"
`.

### CODE REVIEW

**Comment by fuegoio** [comment]
Hey !

Thank you for your interest in my theme :) It is a cool feature but you should consider some improvements I think : 

* I think the text is a bit big aside the small icons, you should maybe try to CSS a bit with for example a `font-size: 14px;`
* Be careful of the **responsivity** of the theme, the icons are going to the top on a mobile, and your text breaks the symetry (maybe change the position on mobile ?)
* Update the exampleSite with a example license, it is the site that is shown on themes.gohugo.io

This is all I can think of now, feel free to ask me anything !

**Comment by Hjdskes** [comment]
> I think the text is a bit big aside the small icons, you should maybe try to CSS a bit with for example a `font-size: 14px;`

Done. As I said, I purposely didn't style things yet. Is there anything else you want to do style-wise? My current theme looks like this, which I also quite like (see https://hjdskes.github.io):

screenshot from 2017-02-21 23-17-35

> Be careful of the responsivity of the theme, the icons are going to the top on a mobile, and your text breaks the symetry (maybe change the position on mobile ?)

Right, I didn't know about this. I think it's quite strange that the icons move to the top of the page; what is the reason for this? Personally, I would prefer them to stay in the bottom.

> Update the exampleSite with a example license, it is the site that is shown on themes.gohugo.io

Done!

**Comment by fuegoio** [comment]
> Done. As I said, I purposely didn't style things yet. Is there anything else you want to do style-wise? My current theme looks like this, which I also quite like (see https://hjdskes.github.io):

I like it too, but I think it would be a bit weird on this theme, because of the color and position. I like the way it is now with the license :)

> Right, I didn't know about this. I think it's quite strange that the icons move to the top of the page; what is the reason for this? Personally, I would prefer them to stay in the bottom.

It was in the original theme and I never really discussed it, I like when it goes at the top because I think that on mobile the Disqus is a blocking section that few will look, and that way everything is condensed at the top and more accessible.

**Comment by Hjdskes** [comment]
Oke, I will see if I can fix the position on mobile.

**Comment by Hjdskes** [comment]
What do you think of this? I quite like it! On a phone it now looks like this:

screenshot from 2017-02-25 18-58-03

On a laptop like this:

screenshot from 2017-02-25 18-58-51

I don't know how to only move the license text to the bottom of the page on mobile. If that is the way you want to go, I'm afraid you'll have to do that yourself.

For my own website, I have overridden the CSS so that the icons and license are always in the bottom of the page and centered as in these pictures. I still think this is the best way to go, but this is up to you of course.

**Comment by fuegoio** [comment]
Hi !

Well, I'm not convinced by the center, because this theme is not 'centered' (the header is not for example). The eye look of the user begins a the top left and should arrive at the bottom right, and for me the icons are more important than the copyright (you search for the copyright but icons have to be on your way to hit you). This is why I propose something like this : 

## Laptop

screenshot from 2017-02-25 20-41-41

## Mobile 

screenshot from 2017-02-25 20-41-49

I now think that icons at the bottom are adapted ;) Don't know what you think but I do like it ! Seems to me better than in the center. If you're satisfied I can commit this on your branch (the [github doc for it](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)), just tell me !

**Comment by Hjdskes** [comment]
> Well, I'm not convinced by the center, because this theme is not 'centered' (the header is not for example). The eye look of the user begins a the top left and should arrive at the bottom right, and for me the icons are more important than the copyright (you search for the copyright but icons have to be on your way to hit you).

That's a good theory, I didn't think of that :)

> If you're satisfied I can commit this on your branch (the github doc for it), just tell me !

Sure, go ahead!

**Comment by fuegoio** [comment]
Okey thx ! If you think that it is ready to merge, tell me :)

**Comment by Hjdskes** [comment]
The footer appears on top of my page content:

screenshot from 2017-02-25 23-36-57

**Comment by Hjdskes** [comment]
Nevermind, that was Google Chrome caching my local hugo server! I think it's good to go! :)

**Comment by Hjdskes** [comment]
Cheers! How fast do you think this will be in a release?

**Comment by fuegoio** [comment]
I just need to fix few things and it will be good I think !

**Pull request merged**
