### PR TITLE
Remove unnecessary analytics conditional

### PR DESCRIPTION
**Pull request by mtn**
Hi!

When looking at how another theme implemented analytics, I found that it's actually not necessary to have an explicit conditional checking if the analytics attribute was set. It seems to be implemented by Hugo itself. I've thus removed the two unnecessary lines.

Sorry for the messy merge. I'm making the pull request to dev in case you want to verify yourself. :elephant:

### CODE REVIEW

**Comment by mtn** [comment]
Err, I switched to master after noticing dev was behind and will leave it for you do do as you wish.

**Comment by fuegoio** [comment]
Hi !

Thanks for your PR, could you just make it looks like one commit from master ? It doesn't matter that it's on dev on master, there is only a README change on master that is not on dev.

**Comment by mtn** [comment]
Correct me if I'm wrong, but I'm not sure I can squash the merge commit. Reduced to 2.

**Comment by fuegoio** [comment]
Done :) Thanks you !

**Pull request merged**
