### PR TITLE
Make the theme compliant with W3C standards

### PR DESCRIPTION
**Pull request by Vipermaseg**
These changes make the theme W3C compliant as far as I checked. I cleaned a couple of unordered lists and changed all section tags I found for div tags.

If you have any questions I am happy to answer.

EDIT: Also, CSS on section plays bad with Isso, which uses them, so after this PR I would then clean the CSS and make Isso display nicely.

### CODE REVIEW

**Comment by fuegoio** [comment]
Hi ! Thanks for your PR, really interesting ! Do you have a link about thoses rules in W3C ? How do you know them ? Do you use a tool for this ?

**Comment by Vipermaseg** [comment]
Yup, would be hell to know "da rules" by memory. https://validator.w3.org/
By W3C compliant, which is understandably ambiguous (sorry), I meant that we pass this test for the HTML5 standard. We don't pass the CSS test, though. 

Sections only fire a warning message, but there are two reasons to change them for divs. One being that Isso uses sections but we have them stylized, and that messes with the padding of the comment section, making it look a bit ugly. The second reason is that section is supposed to have semantic meaning and help with web crawlers and that kind of thing. Check this out too if you have the time https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines

Note that I haven't cleaned the CSS fully, but I'll make more PRs soon if you think it is worth it.

EDIT: I also like this extension to run the validator https://chrome.google.com/webstore/detail/validity/bbicmjjbohdfglopkidebfccilipgeif?utm_source=chrome-app-launcher-info-dialog

**Comment by mtn** [comment]
This was a great idea! I've had it on the back of my mind, but figured it'd be a ton of work to implement.

How are you testing it? Just plugging the templates themselves in, or generating a site and plugging the output in?

**Comment by Vipermaseg** [comment]
You always check on the generated site since it is what really matters to the browser. I use the extension because it is much more convenient to check a local environment.

**Comment by fuegoio** [comment]
Cool ! Seems okey to me. I will be testing this and then merging it if ready.

**Comment by Vipermaseg** [comment]
So, how is it going?

**Comment by mtn** [comment]
@Vipermaseg sorry for the delay, I'll be getting to this soon :fallen_leaf:

**Pull request merged**
