### PR TITLE
Any blog page

### PR DESCRIPTION
**Pull request by Vipermaseg**
With these changes, I add the array "blogs" to the config file, where we can set which tabs should behave like blogs (post in the index and comments at the end).

Github says that we can't automatically merge but it isn't giving me a clear indication of where is the conflict, but I'm confident it will be something minor.

#56

### CODE REVIEW

**Comment by Vipermaseg** [comment]
Ok, so now I see the files with the conflict, but if I check on the commit the diff doesn't show anything strage... I guess it is up to you?... I'm not too sure on this one. Sorry.

**Comment by mtn** [comment]
Thanks for putting this in @Vipermaseg :). This is actually somewhat related to other things I was looking to change. For example, if someone doesn't want to have their "main" tab be called blog, then the tabs get sorted alphabetically. I think all those that are designated as "blogs" should be the first options (horizontally) in the menubar, rather than having a hardcoded default. Just some thoughts.

Will look into this a bit more and merge it soon.

**Comment by mtn** [comment]
Currently, it seems like this change breaks rendering of blog (not content) pages that have no associated posts. An example would be an "about me" section which just displays some text like [this one](https://caspern.github.io/home/). I'm pretty sure that was rendered with the `layouts/section/blog.html` layout, but I don't remember and Hugo's lookup order makes it a bit of work to figure out. I'll poke at it more.

For the future, could you please also keep the changes in a PR to one at most? (where one change could be `section` -> `div`). It makes reviewing the diff and making sure there are no errors easier.

🌳

**Comment by Vipermaseg** [comment]
Currently my blog is down and my memory is a bit shaky, but I'm pretty sure I've tried that and that it should work... The whole point of this feature is to be able to choose which tabs are blogs after all. Sadly I can't look into it right now, you know, exams.

I get what you are saying and that is why even though there is one PR, there is a lot of little commits. That said, I'll do whatever you say is easier for you.

**Comment by mtn** [comment]
Gotcha. It's also possible that I did the merge wrong, so I'll look into that.

Good lucks with exams 🎈

**Comment by seemethere** [comment]
@Vipermaseg you may just want to do a rebase on the current master

**Comment by Vipermaseg** [comment]
Thx @mtn. @seemethere I'll need more time for that. My git-fu is yellow belt at most. I'll come back to this eventually.

**Comment by budui** [comment]
I have try with @Vipermaseg 's commits. Maybe section.html also need to be changed,  to make sure section in "blogs" array have the same behavior as blog.

**Comment by mtn** [comment]
@Vipermaseg Ah, I let this sit for quite awhile. I tried rebasing this onto the current master, but ran into _a lot_ of merge conflicts. The main problem is that there are a lot of (probably good) changes in here that aren't related to the PR. Some, having to do with validation, I thought had even been merged in at some point. But I'm not entirely sure. For the future -- it's much much easier to merge changes that are small and tightly integrated.

Not having the patience (sorry!) I'm going to close this PR, and implement the change. I hope I'm not being too grouchy, and I really appreciate your change, but I think it's easier for me to work my way through each step when I just don't remember what the motivation for some of the unrelated changes was. I'll ping you before merging the change.

**Pull request closed without merging**
