### PR TITLE
404 redesign

### PR DESCRIPTION
**Pull request by mtn**
Alright, this is a first go at the 404 redesign from #45. Depending on what you think of the look, we may want to clean up the template. 🐺 

Screenshot:

screen shot 2017-08-01 at 1 02 24 am

### CODE REVIEW

**Comment by fuegoio** [comment]
Cleaner, and nice yeah. However, I prefer the version you designed in the issue #45 ! Maybe you should try to center the logo and the text :)

**Comment by mtn** [comment]
Sounds good, I'll make some changes later today. In truth, I was being a bit lazy to not have to fight too much against what I got right out of the box. I totally agree regarding the design though, and will make something just like #45.

**Comment by mtn** [comment]
Also, if I remember correctly the reason I didn't use the `header_includes` partial was that it included more than was desired (like the links to blog, about, etc.). I think it might be worth modifying the partial a bit so there's one that just gets the stylesheets and fonts, so that can be used in "minimal" parts of the site. Let me know if you think otherwise, because I'll probably shift it around before this PR is merged to keep the final template clean :)

**Comment by fuegoio** [comment]
If you found useful to separate concerns in the `header_includes` partial you can sure ! The 404 page should be as lightweight as possible.

**Comment by mtn** [comment]
@fuegowolf I've updated the partial to something that more closely resembles the original mockup, with changes to more closely match the general look of the theme (rather than placing things at the top of the window, I centered them on the middle, and I used typography fro the theme). Here's what it looks like now:

screen shot 2017-08-04 at 12 35 35 am

Assuming you generally like it, I think that before merging there should be a change to the relative size of the font and logo. But these are small things and easy to do, so I'll leave it be at the end.

Let me know what you think!

**Comment by fuegoio** [comment]
Impressive ! Sorry not to be invested in this theme as I would. This 404 page is looking really great ! I love the way the logo is dominant in it.

The code is fine too, wonderful work !

Please tell me when it is ready to merge :)

**Review by fuegoio — APPROVED** [review]
Nice work !

**Comment by mtn** [comment]
Cool! If you like the size of the logo relative to the text is good, I think the PR is ready to be merged :)

🐺

**Pull request merged**
