### PR TITLE
 Add Isso support 

### PR DESCRIPTION
**Pull request by vsund**
This PR adds support for comments with [Isso](https://posativ.org/isso/) (on [GitHub](https://github.com/posativ/isso)). To enable it add `issoHost = "comments.example.org"` to your config.

To read more about Isso and how to install, please read: https://posativ.org/isso/docs/

---
This is not Commento, but related though: https://github.com/fuegowolf/cocoa-eh-hugo-theme/issues/34

### CODE REVIEW

**Comment by fuegoio** [comment]
Hi again ! Really cool !

However, I have a question about the case where there is a disqus id and a isso url in the configuration, this will load the two frameworks, but don't you think that it should only be one of them (isso for exemple because it is open source) ?

Thank you again !

**Comment by vsund** [comment]
I'm not sure whether I understand you correctly. Do you mean adding an `if`/`elseif` to only display Isso if both are configured?
If so, I would let this open to the user, so he is able to decide to have both (which is if course a bit strange :D). But no problem to add something to counter this.

Maybe a hint in the wiki is enough? Or more general: What about a "Comments" page in the wiki to quickly document both options? I could write something together tomorrow ;)

---
Another thing: Should PRs get raised against the `dev` branch in every case? I briefly rushed over some old PRs and couldn't find something. Maybe a short note on the readme? :)

**Comment by mtn** [comment]
@vsund I've not been consistent myself, but I believe `dev` is used to stage all changes that are non-trivial and gets merged into `master` after being tested for each release.

**Comment by fuegoio** [comment]
> I'm not sure whether I understand you correctly. Do you mean adding an if/elseif to only display Isso if both are configured?
If so, I would let this open to the user, so he is able to decide to have both (which is if course a bit strange :D). But no problem to add something to counter this.

Yeah I would prefer a small default behavior if someone makes a mistake, feel free to do it or not :+1: 

> Maybe a hint in the wiki is enough? Or more general: What about a "Comments" page in the wiki to quickly document both options? I could write something together tomorrow ;)

Great idea ! I'm not so available by those times, but if you write something I would be happy to add it to the wiki :)

> I've not been consistent myself, but I believe dev is used to stage all changes that are non-trivial and gets merged into master after being tested for each release.

Exactly ;)

**Comment by vsund** [comment]
I'd let this open to the user to avoid logic that disallows some scenarios while it isn't strongly needed :)

I wrote a short [wiki page proposal](https://github.com/fuegowolf/cocoa-eh-hugo-theme/files/1082646/Comments.md.txt) for both systems (click to download, to be added). It's not that much but I don't know what it would need that's not already said at their respective documentations.

**Pull request merged**
