### PR TITLE
Basic support for Mailmunch

### PR DESCRIPTION
**Pull request by alexandre-mbm**

### CODE REVIEW

**Comment by fuegoio** [comment]
Hi !

Thanks for your Pull Request, maybe you could add an example of how to use it, I don't know really well Mailmunch.
Do you think that it is interesting to put a newsletter signup at the bottom of the page ? Like the share buttons on the dev branch.

**Comment by alexandre-mbm** [comment]
No, I think the think of Mailmunch as optional. Yes, I will can give instructions. In really, I would want to make a _partial_ to include the form (this today is done by adding a `<div>` tag inline in posts).

**Comment by fuegoio** [comment]
Yes I think it optional you, but with the `<div>` too with the isset of the variable. You could do the partial too yeah !

**Comment by alexandre-mbm** [comment]
There are forms with predefined position and also of those inline or ad hoc.

**Comment by fuegoio** [comment]
Okey so include it !

**Pull request closed without merging**
