### PR TITLE
A working implementation of social links

### PR DESCRIPTION
**Pull request by mtn**
This is a pull request that follows up on the feature I suggested in #37. I'm not sure if there's a particularly good way to implement this that I'm missing, but here's what I did:

A user would include a `socialLinks` param in their content header (so before this changes is finalized and merged, it should be added to the default archetype). `socialLinks` is an array of arrays, each of which has the social site name as its first param and the absolute link to the content as its second. I did this because it allows for easy iteration in the template, but it produces a few concerns:

1. Typing the name of the social site repeatedly seems cumbersome and error-prone. Maybe it's just better to have a param for each supported site?
2. Absolute links aren't very nice, in my opinion. But it gets worse. If the user provides a proper link, all is well (ex. "https://www.google.com"). But if they provide something like "www.google.com" it is converted to a relative url. There may be a way be a way of dealing with this that I'm not aware of, though. Switching away from the array would make this easier to deal with too. For example, since we know that hacker news refers to content by IDs, the `hackerNews` param could take a content-id, while the `lobste.rs` one could take a title.

Anyways, I'd appreciate your input (and anyone else who follows the theme)! All told, this is how it looks right now:

screen shot 2017-06-09 at 6 13 22 pm

And the relevant corresponding param:

```
socialLinks = [["Hacker News","someAbsUrl"],["Lobsters","someAbsUrl"]]
```

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Comment by fuegoio** [comment]
Hi ! Really thanks you for your PR !

In fact, I don't really like the fact that this is so 'modular'. For me, it would be better if some sites are allowed, like HackerNews and lobste.rs, and to refer to them with the id / title of the thread.

With that, it is giving you the idea to publish to those aggregators in particular, and it is easy to setup. Secondly, it doesn't give the author a way to do phishing or other bad links with a HackerNews label on it.

However your work is really good ! It is very promising. Tell me what you think !

**Comment by mtn** [comment]
Yeah, that's what I'm thinking also. Of course the owner of a site can manipulate the theme in any way they want so phishing would always be possible, but this seems like a much saner default.

I'll have an update pushed this evening!

**Comment by mtn** [comment]
Alright, I've supported Hacker News and Lobste.rs explicitly, and modified the default archetype. Also, after this is finished, (if you want) I can write a wiki page describing the features.

**Comment by fuegoio** [comment]
Everything is good for me ! Really great job :+1: If you want to write the wiki page it would be a pleasure too !

**Comment by mtn** [comment]
Great. I made minor modifications to  the [blog posts](https://github.com/fuegowolf/cocoa-eh-hugo-theme/wiki/Blog-posts) wiki page and created one for [social links](https://github.com/fuegowolf/cocoa-eh-hugo-theme/wiki/Social-Links)!

**Comment by fuegoio** [comment]
Really great thanks you !

**Pull request merged**
