### PR TITLE
Adds author information on blog posts

### PR DESCRIPTION
**Pull request by seemethere**
Simply just adds names based on front matter in the post itself using the `author` parameter.

Can be fully disabled in the `config.toml` with the `noauthor` parameter

### CODE REVIEW

**Comment by fuegoio** [comment]
Hi ! Thanks your for your PR ! Just tested it and it's working great !

However, could you maybe add a little bit of CSS to it ? Font, size, color, etc. ... Have you tried to integrate it in the line with the date and the time needed to read ?

**Comment by seemethere** [comment]
Yup just moved it between the date and the time to read the tag exists and added it to the css to make it align with the other front-matter components.

Here's a screenshot for an example:
screen shot 2017-04-04 at 2 05 48 pm

**Comment by fuegoio** [comment]
Wonderful ! It's very cool thanks you ! Gonna add it to dev and then do a big release with other merges :)

**Comment by seemethere** [comment]
Awesome! Looking forward to it!

**Pull request merged**
