### PR TITLE
Allow css transformations of title in config

### PR DESCRIPTION
**Pull request by evrardjp**
By default the style uppercases the title.
We can add extra css but that might be overkill for just one
change: Not capitalizing the title default.

This allows the title to be fully lowercase, by simply overriding
the theme configuration.

### CODE REVIEW

**Comment by mtn** [comment]
Hm, I don't really like the implementation (but I'm open to being persuaded). The basic reason is I don't like that the parameter literally ends up in the CSS. I think it would be better to have the user choose between several prepared CSS options.

Thoughts?

**Comment by mtn** [comment]
Just to elaborate, I don't like the idea that a valid configuration could result in invalid generated code.

**Comment by evrardjp** [comment]
Agreed that sounds better. It was a quick hack. Let me figure that out.

**Comment by evrardjp** [comment]
For an "invalid" user configuration (with a valid syntax), would you prefer something that silently works by falling back to a valid generated code, or a more aggressive approach to fail ?

**Comment by evrardjp** [comment]
Updated.

**Comment by mtn** [comment]
Hm, so this was broken for my version of Hugo, since the `errorf` function must have been added somewhat recently (but worked fine after upgrading). I don't know the last time I'd upgraded my Hugo version, but I suspect it might be more recent than a typical user.

Nonetheless, I think this is fine to merge. I'm going to make something like a debugging checklist that people can try when things don't build where one of the suggestions can be running with the latest version of Hugo.

**Comment by evrardjp** [comment]
That's up to you :)

**Comment by evrardjp** [comment]
Else you can maybe edit to remote the errorf, and fallback to a safe value instead.  But I think an error is more explicit.

**Comment by mtn** [comment]
Yea, I think so too. I've just changed the parameter name to be a tad more consistent with the lowercase non-delimited other parameters (though I know there are a few ossified inconsistencies already).

Thanks for the contribution!

**Comment by evrardjp** [comment]
yw! Have a good week-end :)

**Pull request merged**
